USE MASTER
GO

--DROP LOGIN Labbd;
CREATE LOGIN Labbd WITH PASSWORD = '**Senha**';
GO

GRANT CONNECT SQL TO Labbd;
GO

USE BIBLIOTECA
GO

--DROP USER Labbd
CREATE USER Labbd FOR LOGIN Labbd;
GO

GRANT EXECUTE ON BIBLIOTECA.dbo.SP_I_BIB_LIVRO TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_U_BIB_LIVRO TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_D_BIB_LIVRO TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_S_BIB_LIVRO TO Labbd;

GRANT EXECUTE ON BIBLIOTECA.dbo.SP_I_BIB_AUTORES TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_U_BIB_AUTORES TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_D_BIB_AUTORES TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_S_BIB_AUTORES TO Labbd;

GRANT EXECUTE ON BIBLIOTECA.dbo.SP_I_BIB_EDITORA TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_U_BIB_EDITORA TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_D_BIB_EDITORA TO Labbd;
GRANT EXECUTE ON BIBLIOTECA.dbo.SP_S_BIB_EDITORA TO Labbd;